// <auto-generated />
using System;
using DonationLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ServerBlazorEF.Data.Migrations
{
    [DbContext(typeof(DonationDbContext))]
    [Migration("20231122070705_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("DonationLibrary.Account", b =>
                {
                    b.Property<int>("AccountNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNo");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNo = 123,
                            City = "Anytown",
                            Country = "USA",
                            Created = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Email = "john.doe@email.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Modified = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "Admin",
                            PostalCode = "12345",
                            Street = "123 Main St"
                        },
                        new
                        {
                            AccountNo = 456,
                            City = "Otherville",
                            Country = "Canada",
                            Created = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "User1",
                            Email = "jane.smith@email.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Modified = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "User1",
                            PostalCode = "67890",
                            Street = "456 Oak St"
                        },
                        new
                        {
                            AccountNo = 789,
                            City = "Sometown",
                            Country = "UK",
                            Created = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "User2",
                            Email = "bob.johnson@email.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            Modified = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "User2",
                            PostalCode = "54321",
                            Street = "789 Pine St"
                        },
                        new
                        {
                            AccountNo = 101,
                            City = "Anotherplace",
                            Country = "Australia",
                            Created = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Email = "alice.williams@email.com",
                            FirstName = "Alice",
                            LastName = "Williams",
                            Modified = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "Admin",
                            PostalCode = "13579",
                            Street = "101 Elm St"
                        });
                });

            modelBuilder.Entity("DonationLibrary.Donation", b =>
                {
                    b.Property<int?>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountNo")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Amount")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentMethodId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransactionTypeId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("TransId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            TransId = 1,
                            AccountNo = 123,
                            Amount = 100.5f,
                            Created = new DateTime(2023, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "User1",
                            Date = new DateTime(2023, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(2023, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "User1",
                            Notes = "Donation for Education",
                            PaymentMethodId = 1,
                            TransactionTypeId = 1
                        },
                        new
                        {
                            TransId = 2,
                            AccountNo = 456,
                            Amount = 75.25f,
                            Created = new DateTime(2023, 1, 11, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "User2",
                            Date = new DateTime(2023, 1, 11, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(2023, 1, 11, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "User2",
                            Notes = "Monthly Subscription",
                            PaymentMethodId = 2,
                            TransactionTypeId = 2
                        },
                        new
                        {
                            TransId = 3,
                            AccountNo = 789,
                            Amount = 50.75f,
                            Created = new DateTime(2023, 1, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Date = new DateTime(2023, 1, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(2023, 1, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "Admin",
                            Notes = "Event Registration",
                            PaymentMethodId = 3,
                            TransactionTypeId = 3
                        },
                        new
                        {
                            TransId = 4,
                            AccountNo = 101,
                            Amount = 120f,
                            Created = new DateTime(2023, 1, 13, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Date = new DateTime(2023, 1, 13, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            Modified = new DateTime(2023, 1, 13, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "Admin",
                            Notes = "General Donation",
                            PaymentMethodId = 4,
                            TransactionTypeId = 1
                        });
                });

            modelBuilder.Entity("DonationLibrary.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            PaymentMethodId = 1,
                            Created = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Modified = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "Admin",
                            Name = "Credit Card"
                        },
                        new
                        {
                            PaymentMethodId = 2,
                            Created = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "User1",
                            Modified = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "User1",
                            Name = "PayPal"
                        },
                        new
                        {
                            PaymentMethodId = 3,
                            Created = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "User2",
                            Modified = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "User2",
                            Name = "Bank Transfer"
                        },
                        new
                        {
                            PaymentMethodId = 4,
                            Created = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Modified = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "Admin",
                            Name = "Cash"
                        });
                });

            modelBuilder.Entity("DonationLibrary.TransactionType", b =>
                {
                    b.Property<int>("TransactionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionTypeId");

                    b.ToTable("TransactionTypes");

                    b.HasData(
                        new
                        {
                            TransactionTypeId = 1,
                            Created = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Description = "Donation for a cause",
                            Modified = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "Admin",
                            Name = "Donation"
                        },
                        new
                        {
                            TransactionTypeId = 2,
                            Created = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "User1",
                            Description = "Monthly subscription payment",
                            Modified = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "User1",
                            Name = "Subscription"
                        },
                        new
                        {
                            TransactionTypeId = 3,
                            Created = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "User2",
                            Description = "Event registration fee",
                            Modified = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "User2",
                            Name = "Event"
                        },
                        new
                        {
                            TransactionTypeId = 4,
                            Created = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Description = "General donation",
                            Modified = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "Admin",
                            Name = "General"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
